apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-backend
  namespace: rails-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-backend
  template:
    metadata:
      labels:
        app: rails-backend
    spec:
      initContainers:
        - name: database-prepare
          image: harshparmar009/rails-task-backend:v1
          command:
            - sh
            - -c
            - bin/rails db:prepare
          env:
            - name: RAILS_ENV
              value: production
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: 6575cf6f8fc1c0036f27e841a90c3207f98043bafb4d963e471908ea12d6726798d24b6b0516fb93c14ed669784dcc78c29dd3cdf30221d2fe5e0f7d5bb95f71      

      containers:
        - name: rails-backend
          image: harshparmar009/rails-task-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: RAILS_ENV
              value: production
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: 6575cf6f8fc1c0036f27e841a90c3207f98043bafb4d963e471908ea12d6726798d24b6b0516fb93c14ed669784dcc78c29dd3cdf30221d2fe5e0f7d5bb95f71      
          readinessProbe:
            httpGet:
              path: /up
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /up
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: rails-backend
  namespace: rails-task
spec:
  selector:
    app: rails-backend
  ports:
    - port: 80
      targetPort: 80
